export const DEPARTMENT_MAPPING = [
  {
    code: '​DEP00001',
    hrisId: 'BOD',
    hrisName: 'BOD',
    scoreId: 1,
    scoreName: 'BOD',
  },
  {
    code: '​DEP00003',
    hrisId: 'BRANDING',
    hrisName: 'BRANDING',
    scoreId: 2,
    scoreName: 'BRANDING',
  },
  {
    code: '​DEP00003',
    hrisId: 'BL',
    hrisName: 'BL',
    scoreId: 3,
    scoreName: 'Buyer - Logistics',
  },
  {
    code: '​DEP00003',
    hrisId: 'FIN',
    hrisName: 'FIN',
    scoreId: 4,
    scoreName: 'FIN',
  },
  {
    code: '​DEP00003',
    hrisId: 'GIS',
    hrisName: 'GIS',
    scoreId: 5,
    scoreName: 'GIS',
  },
  {
    code: '​DEP00003',
    hrisId: 'HR-ADM',
    hrisName: 'HR-ADM',
    scoreId: 6,
    scoreName: 'HR-ADM',
  },
  {
    code: '​DEP00003',
    hrisId: 'NW',
    hrisName: 'NW',
    scoreId: 7,
    scoreName: 'Network',
  },
  {
    code: '​DEP00003',
    hrisId: 'SYS',
    hrisName: 'SYS',
    scoreId: 8,
    scoreName: 'System',
  },
  {
    code: '​DEP00003',
    hrisId: 'DNA',
    hrisName: 'DNA',
    scoreId: 9,
    scoreName: 'DnA',
  },
  {
    code: '​DEP00003',
    hrisId: 'PM',
    hrisName: 'PM',
    scoreId: 10,
    scoreName: 'PM',
  },
  {
    code: '​DEP00003',
    hrisId: 'QA',
    hrisName: 'QA',
    scoreId: 11,
    scoreName: 'QA',
  },
  {
    code: '​DEP00003',
    hrisId: 'SALES',
    hrisName: 'SALES',
    scoreId: 12,
    scoreName: 'Sales',
  },
  {
    code: '​DEP00003',
    hrisId: 'SALES-TELCO',
    hrisName: 'SALES-TELCO',
    scoreId: 12,
    scoreName: 'Sales-Telco',
  },
  {
    code: '​DEP00003',
    hrisId: 'SOL',
    hrisName: 'SOL',
    scoreId: 13,
    scoreName: 'Solution',
  },
  {
    code: '​DEP00003',
    hrisId: 'SERVICE',
    hrisName: 'SERVICE',
    scoreId: 14,
    scoreName: 'Services',
  },
  {
    code: '​DEP00003',
    hrisId: 'SERVICE',
    hrisName: 'SERVICE',
    scoreId: 15,
    scoreName: 'SDM',
  },
  {
    code: '​DEP00003',
    hrisId: 'TECH',
    hrisName: 'TECH',
    scoreId: 16,
    scoreName: 'TECH',
  },
  {
    code: '​DEP00003',
    hrisId: 'BANKING SOLUTION',
    hrisName: 'BANKING SOLUTION',
    scoreId: 17,
    scoreName: 'BANKING',
  },
  {
    code: '​DEP00003',
    hrisId: 'MOBILE',
    hrisName: 'MOBILE',
    scoreId: 18,
    scoreName: 'Mobile',
  },
  {
    code: '​DEP00003',
    hrisId: 'OTHERS',
    hrisName: 'OTHERS',
    scoreId: 19,
    scoreName: 'Others',
  },
  {
    code: '​DEP00003',
    hrisId: 'SALES-NONTELCO',
    hrisName: 'SALES-NONTELCO',
    scoreId: 12,
    scoreName: 'Sales-NonTelco',
  },
  {
    code: '​DEP00003',
    hrisId: 'SALES-TELCO',
    hrisName: 'SALES-TELCO',
    scoreId: 12,
    scoreName: 'Sales-Telco',
  },
  {
    code: '​DEP00003',
    hrisId: 'SE',
    hrisName: 'SE',
    scoreId: 12,
    scoreName: 'SE',
  },
  {
    code: '​DEP00003',
    hrisId: 'TENDER',
    hrisName: 'TENDER',
    scoreId: 12,
    scoreName: 'Tender',
  },
];