export function buildSyncMail(data: {
  system: string;
  total: number;
  success: number;
  failed: number;
  errors: any[];
}) {
  return `
    <h2>HRIS Synchronization Report</h2>

    <table border="1" cellpadding="6" cellspacing="0">
      <tr>
        <td><b>System</b></td>
        <td>${data.system}</td>
      </tr>

      <tr>
        <td><b>Time</b></td>
        <td>${new Date().toLocaleString()}</td>
      </tr>

      <tr>
        <td><b>Total</b></td>
        <td>${data.total}</td>
      </tr>

      <tr>
        <td><b>Success</b></td>
        <td style="color:green">${data.success}</td>
      </tr>

      <tr>
        <td><b>Failed</b></td>
        <td style="color:red">${data.failed}</td>
      </tr>
    </table>

    <br/>

    ${
      data.failed > 0
        ? `
        <h3>Failed Records</h3>

        <table border="1" cellpadding="5" cellspacing="0">
          <tr>
            <th>Employee Code</th>
            <th>Employee Name</th>
            <th>Error</th>
          </tr>

          ${data.errors
            .map(
              item => `
              <tr>
                <td>${item.code}</td>
                <td>${item.name}</td>
                <td>${item.message}</td>
              </tr>
            `,
            )
            .join('')}
        </table>
      `
        : '<h3 style="color:green">Synchronization completed successfully.</h3>'
    }

    <br/>

    <small>This email is automatically generated by HRIS Integration.</small>
  `;
}